package org.bson.codecs.pojo.entities;

import java.time.Instant;

public final class VoidModel {
    private Instant expiredAt;

    public static void getExpiredAt$annotations() { // automatically generated by a third-party
    }

    public final Instant getExpiredAt() {
        return this.expiredAt;
    }

    public final void setExpiredAt(Instant expiredAt) {
        this.expiredAt = expiredAt;
    }
}
